import type { NextPage } from 'next'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { getSortedTravelData } from '../lib/travels'
import { Logs } from '../types/Logs'

export const getStaticProps: GetStaticProps = async (context) => {
    const allLogsData = await getSortedTravelData()
    return {
        props: {
            allLogsData,
        },
    }
}

const Home: NextPage = ({ allLogsData }: InferGetStaticPropsType<typeof getStaticProps>) => {
    return (
        <>
            <Head>
                <title>My Working Holiday - MyWH</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <h1>Home</h1>
            {allLogsData.length ? (
                <div>
                    <ul>
                        {allLogsData.map(({ id, date, title }: Logs) => (
                            <li key={id}>
                                {title}
                                <br />
                                {date}
                            </li>
                        ))}
                    </ul>
                </div>
            ) : (
                <div>No Date</div>
            )}
        </>
    )
}

export default Home
