import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>My Working Holiday - MyWH</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <h1>Home</h1>
            <div>
                <ul>
                    <li>
                        <Link href={`/about`}>
                            <a>About</a>
                        </Link>
                    </li>
                    <li>
                        <Link href={`/blog`}>
                            <a>Blog</a>
                        </Link>
                    </li>
                </ul>
            </div>
        </>
    )
}

export default Home
